<?php
$allocated=0; $legacy=false;
foreach ($items as $item) { if ($item['excluido_em']!==null) { continue; } if ($item['total_centavos']===null) { $legacy=true; } else { $allocated+=(int)$item['total_centavos']; } }
$active=$record['excluido_em']===null;
?>
<section class="relatorio">
<p><a href="<?= e(url('contrato')) ?>">Contratos</a> · <a href="<?= e(url('contrato/imprimir/'.$record['id'])) ?>" target="_blank" rel="noopener">Imprimir contrato</a></p>
<h2><?= e($record['titulo']) ?> <?= !$active ? '(excluído)' : '' ?></h2>
<p>Fornecedor: <?= e($record['fornecedor'] ?? 'Não informado') ?> · Valor contratado: <?= e(Contrato::money($record['valor_centavos']===null ? null : (int)$record['valor_centavos'])) ?></p>
<p>Itens distribuídos: <?= $legacy ? 'Revisão de valores legados pendente' : e(Contrato::money($allocated)) ?> · Saldo contratual: <?= $legacy || $record['valor_centavos']===null ? 'Revisão pendente' : e(Contrato::money((int)$record['valor_centavos']-$allocated)) ?></p>
<?php if ($active): ?><p><a class="btn btn-outline-primary" href="<?= e(url('contrato/editar/'.$record['id'])) ?>">Editar dados gerais</a></p><?php endif; ?>
<?php if ($record['valor_centavos']===null || $legacy): ?><div class="warning-message" role="status">Dados anteriores à migração: valores REAL originais foram preservados. A conciliação financeira precisa de revisão administrativa antes de incluir ou alterar itens.</div><?php endif; ?>
<?php if ($isAdmin && $active && $record['valor_centavos']===null): ?><details><summary>Conciliar valor contratado legado</summary><p>Confira os documentos de origem. Os itens devem ser conciliados primeiro; a operação é auditada.</p><form method="post" action="<?= e(url('contrato/conciliar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="produto" value=""><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><label>Valor confirmado R$ <input name="valor" inputmode="decimal" required></label><button class="btn btn-primary">Conciliar</button></form></details><?php endif; ?>
</section>
<?php foreach ($sheets as $sheet): ?>
<section class="relatorio" id="folha-<?= (int)$sheet['id'] ?>">
<div class="section-head"><div><h2>Folha <?= (int)$sheet['numero_pagina'] ?> <?= $sheet['excluido_em']!==null ? '(excluída)' : '' ?></h2><p>Total: <?= e(Contrato::money($sheet['valor_centavos']===null ? null : (int)$sheet['valor_centavos'])) ?> · Faturamento: <?= e($sheet['data_faturamento'] ?? 'não registrado') ?></p></div><a href="<?= e(url('contrato/imprimir/'.$record['id'].'?folha='.$sheet['id'])) ?>" target="_blank" rel="noopener">Imprimir folha</a></div>
<p><?= nl2br(e($sheet['observacao'] ?? '')) ?></p>
<div class="table-scroll"><table class="table"><thead><tr><th>Produto</th><th>Quantidade contratada</th><th>Preço unitário</th><th>Total</th><th>Saldo físico</th><th>Limites</th><th></th></tr></thead><tbody>
<?php foreach ($items as $item): if ((int)$item['numero_pagina']!==(int)$sheet['numero_pagina']) { continue; } $pending=$item['estoque_inicializado']==0; $balance=(int)$item['saldo']; ?>
<tr><td><?= e($item['nome_produto']) ?><?= $item['excluido_em']!==null ? ' (excluído)' : '' ?><br><small><?= e($item['marca'] ?? '') ?> · <?= e($item['unidade']) ?></small></td><td><?= e($item['quantidade_contratada'] ?? $item['quantidade']) ?></td><td><?= e(Contrato::money($item['preco_centavos']===null ? null : (int)$item['preco_centavos'])) ?></td><td><?= e(Contrato::money($item['total_centavos']===null ? null : (int)$item['total_centavos'])) ?></td><td><?= $pending ? 'Abertura pendente' : $balance.' '.e($item['unidade']) ?><?php if (!$pending): ?><br><strong><?= $balance===0 ? 'Sem saldo' : ($balance<=(int)$item['estoque_minimo'] ? 'Atenção: no mínimo ou abaixo' : 'Normal') ?></strong><?php endif; ?></td><td><?= $pending ? '—' : (int)$item['estoque_minimo'].' / '.(int)$item['estoque_maximo'] ?></td><td><a href="<?= e(url('contrato/historico/'.$item['id'])) ?>">Histórico</a></td></tr>
<?php if ($active && $sheet['excluido_em']===null && $item['excluido_em']===null): ?>
<tr><td colspan="7">
<?php if ($isAdmin && $item['total_centavos']===null): ?><details><summary>Conciliar item legado</summary><p>Confirme a quantidade inteira e o preço unitário contra os documentos. O valor original permanece registrado.</p><form method="post" action="<?= e(url('contrato/conciliar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><label>Quantidade contratada <input name="quantidade" type="number" min="1" required></label><label>Preço unitário R$ <input name="preco" inputmode="decimal" required></label><button class="btn btn-primary">Conciliar item</button></form></details><?php endif; ?>
<details><summary>Editar produto</summary><form method="post" action="<?= e(url('contrato/produto/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><label>Nome <input name="nome" required value="<?= e($item['nome_produto']) ?>"></label><label>Marca <input name="marca" value="<?= e($item['marca'] ?? '') ?>"></label><label>Unidade <input name="unidade" required value="<?= e($item['unidade']) ?>"></label><label>Quantidade contratada <input name="quantidade" type="number" min="1" required value="<?= e($item['quantidade_contratada'] ?? $item['quantidade']) ?>"></label><label>Preço R$ <input name="preco" required value="<?= e($item['preco_centavos']===null ? '' : number_format((int)$item['preco_centavos']/100,2,',','')) ?>"></label><button class="btn btn-primary">Salvar produto</button></form></details>
<details><summary>Estoque e limites</summary><form method="post" action="<?= e(url('contrato/estoque/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><label>Mínimo <input name="minimo" type="number" min="0" required value="<?= e($item['estoque_minimo'] ?? '0') ?>"></label><label>Máximo <input name="maximo" type="number" min="1" required value="<?= e($item['estoque_maximo'] ?? '') ?>"></label><?php if ($pending && ($isAdmin || !$item["legado"])): ?><label>Saldo de abertura conferido (opcional) <input name="abertura" type="number" min="0"></label><?php else: ?><input type="hidden" name="abertura" value=""><?php endif; ?><button class="btn btn-primary">Salvar limites</button></form></details>
<?php if (!$pending): ?><details><summary>Registrar entrada ou saída</summary><form method="post" action="<?= e(url('contrato/movimentar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><label>Tipo <select name="tipo"><option value="entrada">Entrada</option><option value="saida">Saída</option></select></label><label>Quantidade positiva <input name="quantidade" type="number" min="1" required></label><label>Origem ou destino <input name="motivo" minlength="3" maxlength="300" required></label><button class="btn btn-primary">Registrar</button></form></details><?php endif; ?>
<?php if ($isAdmin && !$pending): ?><details><summary>Estornar movimento</summary><form method="post" action="<?= e(url('contrato/movimentar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="tipo" value="estorno"><input type="hidden" name="quantidade" value="1"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><label>ID do movimento original <input name="original" type="number" min="1" required></label><label>Justificativa <input name="motivo" minlength="3" maxlength="300" required></label><button class="btn btn-warning">Estornar</button></form></details><?php endif; ?>
<form method="post" action="<?= e(url('contrato/excluir/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><label><input type="checkbox" name="confirmar" value="1" required> Confirmo a exclusão lógica deste produto</label><button class="btn btn-outline-danger">Excluir produto</button></form>
</td></tr><?php endif; ?>
<?php endforeach; ?></tbody></table></div>
<?php if ($active && $sheet['excluido_em']===null): ?>
<details><summary>Adicionar produto</summary><form method="post" action="<?= e(url('contrato/produto/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="produto" value=""><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><label>Nome <input name="nome" required maxlength="150"></label><label>Marca <input name="marca" maxlength="100"></label><label>Unidade <input name="unidade" required maxlength="30" value="un"></label><label>Quantidade contratada <input name="quantidade" type="number" min="1" required></label><label>Preço unitário R$ <input name="preco" inputmode="decimal" required></label><button class="btn btn-primary">Adicionar</button></form></details>
<details><summary>Editar observação</summary><form method="post" action="<?= e(url('contrato/editar-folha/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$sheet['revisao'] ?>"><textarea name="observacao" maxlength="2000" class="form-control"><?= e($sheet['observacao'] ?? '') ?></textarea><button class="btn btn-primary">Salvar observação</button></form></details>
<details><summary>Faturamento documental</summary><form method="post" action="<?= e(url('contrato/faturar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$sheet['revisao'] ?>"><label>Data <input type="date" name="data" value="<?= e($sheet['data_faturamento'] ?? '') ?>"></label><label>Motivo de correção <input name="motivo" maxlength="180"></label><button class="btn btn-primary">Salvar faturamento</button></form></details>
<form method="post" action="<?= e(url('contrato/folha/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="copiar" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><input type="hidden" name="observacao" value=""><button class="btn btn-outline-primary">Duplicar folha e itens, sem estoque nem faturamento</button></form>
<form method="post" action="<?= e(url('contrato/excluir/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><label><input type="checkbox" name="confirmar" value="1" required> Confirmo a exclusão lógica desta folha</label><button class="btn btn-outline-danger">Excluir folha</button></form>
<?php endif; ?>
</section>
<?php endforeach; ?>
<?php if ($active): ?><section class="relatorio"><h2>Nova folha</h2><form method="post" action="<?= e(url('contrato/folha/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="copiar" value=""><input type="hidden" name="chave" value=""><label for="observacao">Observação</label><textarea id="observacao" name="observacao" maxlength="2000" class="form-control"></textarea><button class="btn btn-primary">Adicionar folha</button></form></section>
<section class="relatorio"><h2>Excluir contrato</h2><p>O registro e o histórico continuarão disponíveis. É preciso destinar todo saldo físico antes.</p><form method="post" action="<?= e(url('contrato/excluir/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><label><input type="checkbox" name="confirmar" value="1" required> Confirmo a exclusão lógica</label><button class="btn btn-outline-danger">Excluir contrato</button></form></section><?php endif; ?>
