<?php
$allocated=0; $legacy=false;
foreach ($items as $item) { if ($item['excluido_em']!==null) { continue; } if ($item['total_centavos']===null) { $legacy=true; } else { $allocated+=(int)$item['total_centavos']; } }
$active=$record['excluido_em']===null;
$activeSheets = array_values(array_filter($sheets, static fn (array $sheet): bool => $sheet['excluido_em'] === null));
$billedSheets = count(array_filter($activeSheets, static fn (array $sheet): bool => $sheet['data_faturamento'] !== null));
$query=[];
if (isset($_GET['busca']) && is_string($_GET['busca'])) { $query['busca']=$_GET['busca']; }
if (($_GET['situacao'] ?? '')==='excluidos') { $query['situacao']='excluidos'; }
if (isset($_GET['pagina']) && filter_var($_GET['pagina'],FILTER_VALIDATE_INT)) { $query['pagina']=$_GET['pagina']; }
$back='contrato'.($query ? '?'.http_build_query($query) : '');
$formatDate=static function (?string $value,bool $dateOnly=false): string {
    if (!$value) { return 'Não registrado'; }
    try { return $dateOnly ? (new DateTimeImmutable($value))->format('d/m/Y') :
        (new DateTimeImmutable($value,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone(Config::string('APP_TIMEZONE','America/Cuiaba')))->format('d/m/Y H:i'); }
    catch (Exception) { return 'Data indisponível'; }
};
$draft=$draft ?? null;
$matchesDraft=static function(string $operation,int $resource) use ($draft): bool {
    return is_array($draft) && $draft['operation']===$operation && (int)($draft['item'] ?: $draft['sheet'])===$resource;
};
$draftValue=static function(string $operation,int $resource,string $field,mixed $current='') use ($draft,$matchesDraft): string {
    if ($matchesDraft($operation,$resource) && !$draft['conflict'] && array_key_exists($field,$draft['fields'])) { return $draft['fields'][$field]; }
    return (string)($current ?? '');
};
$draftOpen=static fn(string $operation,int $resource): string => $matchesDraft($operation,$resource) ? ' open' : '';
$draftNotice=static function(string $operation,int $resource,array $current) use ($draft,$matchesDraft): void {
    if (!$matchesDraft($operation,$resource)) { return; }
    if ($draft['message']!=='') { echo '<p class="error-message" role="alert">'.e($draft['message']).'</p>'; }
    $labels=['nome'=>'Nome','marca'=>'Marca','unidade'=>'Unidade','quantidade'=>'Quantidade','preco'=>'Preço unitário R$',
        'observacao'=>'Observação','minimo'=>'Mínimo','maximo'=>'Máximo','abertura'=>'Saldo de abertura',
        'confirmar_abertura'=>'Confirmação da abertura','confirmar'=>'Confirmação da contagem física',
        'tipo'=>'Tipo de movimento','motivo'=>'Justificativa','original'=>'Movimento original','data'=>'Data','faturado'=>'Pedido faturado'];
    if (!$draft['conflict']) {
        echo '<p class="warning-message" role="status">Preenchimento recuperado. A tentativa não foi salva; revise os campos antes de enviar.</p>';
        foreach ($draft['fields'] as $field=>$value) {
            $invalidNumber=in_array($field,['quantidade','minimo','maximo','abertura','original'],true) && $value!=='' && filter_var($value,FILTER_VALIDATE_INT)===false;
            $date=$field==='data' && $value!=='' ? DateTimeImmutable::createFromFormat('!Y-m-d',$value) : null;
            $invalidDate=$field==='data' && $value!=='' && (!$date || $date->format('Y-m-d')!==$value);
            if ($invalidNumber || $invalidDate) { echo '<p>'.e($labels[$field]).' — tentativa não salva: <strong>'.e($value).'</strong></p>'; }
        }
        return;
    }
    echo '<div class="warning-message" role="alert"><p><strong>O registro mudou desde que o formulário foi aberto.</strong> Os campos abaixo usam os dados atuais. Sua tentativa não salva está disponível para conferência; revise e preencha expressamente as alterações desejadas.</p><div class="table-scroll"><table class="table"><thead><tr><th>Campo</th><th>Dados atuais</th><th>Tentativa não salva</th></tr></thead><tbody>';
    foreach ($draft['fields'] as $field=>$value) {
        echo '<tr><th>'.e($labels[$field] ?? $field).'</th><td>'.nl2br(e((string)($current[$field] ?? 'Não registrado'))).'</td><td>'.nl2br(e($value)).'</td></tr>';
    }
    echo '</tbody></table></div></div>';
};
$formContextField='<input type="hidden" name="_form_context" value="'.e($formContext ?? bin2hex(random_bytes(16))).'">';
$unavailableCurrent=is_array($draft) ? ($draft['current'] ?? []) : [];
if (is_array($draft) && $draft['unavailable']) {
    $unavailableCurrent['nome']=$unavailableCurrent['nome_produto'] ?? '';
    $unavailableCurrent['preco']=isset($unavailableCurrent['preco_centavos']) ? number_format((int)$unavailableCurrent['preco_centavos']/100,2,',','') : '';
    $unavailableCurrent['minimo']=$unavailableCurrent['estoque_minimo'] ?? '';
    $unavailableCurrent['maximo']=$unavailableCurrent['estoque_maximo'] ?? '';
    $unavailableCurrent['data']=$unavailableCurrent['data_faturamento'] ?? '';
    if (in_array($draft['operation'],['editar-produto','adicionar-produto'],true)) { $unavailableCurrent['quantidade']=$unavailableCurrent['quantidade_contratada'] ?? ''; }
    elseif (in_array($draft['operation'],['conferir-abertura','movimentar'],true)) { $unavailableCurrent['quantidade']='Saldo registrado atual: '.($unavailableCurrent['saldo'] ?? 'indisponível').' '.($unavailableCurrent['unidade'] ?? ''); }
}
?>
<nav class="contract-detail-actions" aria-label="Ações do pedido"><a class="btn-secondary" href="<?= e(url($back)) ?>">Voltar</a><?php if ($active): ?><a class="btn-warning" href="<?= e(url('contrato/editar/'.$record['id'])) ?>">✏️ Editar Geral</a><?php endif; ?><a class="btn-primary contract-print-link" href="<?= e(url('contrato/imprimir/'.$record['id'])) ?>" target="_blank" rel="noopener">🖨️ Imprimir Pedido</a></nav>
<section class="relatorio contract-detail-overview <?= count($activeSheets) > 0 && $billedSheets === count($activeSheets) ? 'contract-all-paid' : '' ?>">
<div class="contract-detail-title-row"><div><h2><?= e($record['titulo']) ?> <?= !$active ? '(excluído)' : '' ?></h2>
<span class="contract-pill <?= count($activeSheets) > 0 && $billedSheets === count($activeSheets) ? 'paid' : 'pending' ?>"><?= $billedSheets ?> de <?= count($activeSheets) ?> nota(s) faturada(s)</span>
<small class="contract-billing-hint">O faturamento é controlado individualmente por nota.</small></div>
<p class="contract-detail-supplier">Fornecedor: <?= e($record['fornecedor'] ?? 'Não informado') ?><?php if (!$active): ?><br>Excluído em <?= e($formatDate($record['excluido_em'])) ?> por <?= e($record['excluido_por_nome'] ?? 'Usuário indisponível') ?><?php endif; ?></p></div>
<div class="contract-detail-metrics"><div><span>Teto do Pedido</span><strong><?= e(Contrato::money($record['valor_centavos']===null ? null : (int)$record['valor_centavos'])) ?></strong></div><div><span>Total Gasto (Todas as notas)</span><strong><?= $legacy ? 'Revisão pendente' : e(Contrato::money($allocated)) ?></strong></div><div><span>Saldo Final Restante</span><strong class="contract-balance-remaining"><?= $legacy || $record['valor_centavos']===null ? 'Revisão pendente' : e(Contrato::money((int)$record['valor_centavos']-$allocated)) ?></strong></div></div>
<?php if ($record['valor_centavos']===null || $legacy): ?><div class="warning-message" role="status">Valores anteriores precisam de conferência administrativa com os documentos antes de incluir ou alterar produtos.</div><?php endif; ?>
<?php if ($isAdmin && $active && $record['valor_centavos']===null): ?><details><summary>Conciliar valor contratado legado</summary><p>Confira os documentos de origem. Os itens devem ser conciliados primeiro; a operação é auditada.</p><form method="post" action="<?= e(url('contrato/conciliar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value=""><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><label>Valor confirmado R$ <input name="valor" inputmode="decimal" required></label><button class="btn btn-primary">Conciliar</button></form></details><?php endif; ?>
</section>
<?php if (is_array($draft) && $draft['unavailable']): ?><section class="relatorio" id="draft-review"><h2>Tentativa não salva</h2><p>O pedido, a nota ou o produto está indisponível para alteração. Confira os dados atuais e a tentativa preservada. Nenhuma alteração será reaplicada.</p><?php $draftNotice($draft['operation'],(int)($draft['item'] ?: $draft['sheet']),$unavailableCurrent); ?></section><?php endif; ?>
<?php if ($sheets !== []): ?><nav class="modulo5-tabs" aria-label="Notas do pedido" data-contract-tabs><?php foreach ($sheets as $sheet): ?><a class="<?= $sheet['data_faturamento'] !== null ? 'contract-tab-paid' : '' ?>" href="#folha-<?= (int)$sheet['id'] ?>">Nota <?= (int)$sheet['numero_pagina'] ?></a><?php endforeach; ?><?php if ($active): ?><form method="post" action="<?= e(url('contrato/folha/'.$record['id'])) ?>" data-confirm-status="Deseja adicionar uma nova nota a este pedido?"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="copiar" value=""><input type="hidden" name="chave" value=""><input type="hidden" name="observacao" value=""><button type="submit" class="contract-add-note-tab" aria-label="Adicionar nota">➕</button></form><?php endif; ?></nav><?php endif; ?>
<?php foreach ($sheets as $sheet): ?>
<section class="relatorio modulo5-sheet contract-note-panel <?= $sheet['data_faturamento'] !== null ? 'contract-note-paid' : '' ?>" id="folha-<?= (int)$sheet['id'] ?>">
<div class="section-head contract-note-heading"><div class="contract-note-intro"><h3>Itens da nota <?= (int)$sheet['numero_pagina'] ?> <?= $sheet['excluido_em']!==null ? '(excluída)' : '' ?></h3><div class="contract-note-meta"><span>Total acumulado desta nota: <strong><?= e(Contrato::money($sheet['valor_centavos']===null ? null : (int)$sheet['valor_centavos'])) ?></strong></span><span class="contract-pill <?= $sheet['data_faturamento'] !== null ? 'paid' : 'pending' ?>"><?= $sheet['data_faturamento'] !== null ? 'Pedido faturado' : 'Não faturada' ?></span></div></div>
<div class="contract-note-toolbar">
<?php if ($active && $sheet['excluido_em']===null): ?>
<details id="billing-note-<?= (int)$sheet['id'] ?>" class="contract-billing-inline" open><summary>Faturamento</summary><?php $draftNotice('faturar',(int)$sheet['id'],['data'=>$sheet['data_faturamento'] ?? '','faturado'=>$sheet['data_faturamento']!==null ? '1' : '']); ?>
<form method="post" action="<?= e(url('contrato/faturar/'.$record['id'])) ?>" class="contract-status-form">
<input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="_billing_form" value="1"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$sheet['revisao'] ?>">
<label class="contract-check-inline"><input type="checkbox" name="faturado" value="1"<?= $draftValue('faturar',(int)$sheet['id'],'faturado',$sheet['data_faturamento']!==null ? '1' : '')==='1' ? ' checked' : '' ?>><span>Pedido faturado</span></label>
<label class="contract-status-date"><a href="#billing-note-<?= (int)$sheet['id'] ?>" data-open-details>Data para faturamento</a><input type="date" name="data" value="<?= e($draftValue('faturar',(int)$sheet['id'],'data',$sheet['data_faturamento'] ?? '')) ?>"></label>
<?php if ($sheet['data_faturamento']!==null || $matchesDraft('faturar',(int)$sheet['id'])): ?><label class="contract-status-date contract-billing-reason">Motivo de correção<input name="motivo" maxlength="180" value="<?= e($draftValue('faturar',(int)$sheet['id'],'motivo')) ?>"></label><?php else: ?><input type="hidden" name="motivo" value=""><?php endif; ?>
<button class="btn-secondary contract-btn-sm">Confirmar</button></form></details>
<a class="btn-primary" href="#add-product-<?= (int)$sheet['id'] ?>" data-open-details>+ Adicionar Produto</a>
<?php endif; ?>
<a class="btn-secondary" href="<?= e(url('contrato/imprimir/'.$record['id'].'?folha='.$sheet['id'])) ?>" target="_blank" rel="noopener">🖨️ Imprimir nota</a>
<?php if ($active && $sheet['excluido_em']===null): ?><form method="post" action="<?= e(url('contrato/folha/'.$record['id'])) ?>" data-confirm-status="Duplicar esta nota e seus produtos, sem estoque nem faturamento?"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="copiar" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><input type="hidden" name="observacao" value=""><button class="btn-secondary">📄 Duplicar nota</button></form><a class="btn-danger" href="#delete-note-<?= (int)$sheet['id'] ?>" data-open-details>🗑️ Apagar nota</a><?php endif; ?>
</div></div>
<?php if ($active && $sheet['excluido_em']===null): ?>
<details id="add-product-<?= (int)$sheet['id'] ?>" class="contract-inline-product"<?= $draftOpen('adicionar-produto',(int)$sheet['id']) ?>><summary>Adicionar produto</summary><h4>Novo item para a nota #<?= (int)$sheet['numero_pagina'] ?></h4><?php $draftNotice('adicionar-produto',(int)$sheet['id'],[]); ?>
<form method="post" action="<?= e(url('contrato/produto/'.$record['id'])) ?>" class="contract-product-grid"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="produto" value=""><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>">
<label>Produto<input name="nome" required maxlength="150" value="<?= e($draftValue('adicionar-produto',(int)$sheet['id'],'nome')) ?>"></label><label>Marca<input name="marca" maxlength="100" placeholder="Ex: Chamex" value="<?= e($draftValue('adicionar-produto',(int)$sheet['id'],'marca')) ?>"></label>
<label>Unidade<input name="unidade" required maxlength="30" list="product-units-<?= (int)$sheet['id'] ?>" value="<?= e($draftValue('adicionar-produto',(int)$sheet['id'],'unidade','un')) ?>"><datalist id="product-units-<?= (int)$sheet['id'] ?>"><option value="KG"><option value="L"><option value="UN"><option value="PCT"></datalist></label>
<label title="Quantidade contratada">Qtd<input name="quantidade" type="number" min="1" required value="<?= e($draftValue('adicionar-produto',(int)$sheet['id'],'quantidade','1')) ?>"></label><label>Valor Unit.<input name="preco" inputmode="decimal" required value="<?= e($draftValue('adicionar-produto',(int)$sheet['id'],'preco')) ?>"></label><div class="contract-inline-actions"><button class="btn-primary">Salvar</button><button type="button" class="btn-secondary" data-close-details="add-product-<?= (int)$sheet['id'] ?>" aria-label="Fechar formulário de produto">X</button></div></form></details>
<?php endif; ?>
<div class="table-scroll"><table class="table tabela-filtrada contract-products-table"><thead><tr><th>Descrição do Produto</th><th>Marca</th><th>Unid.</th><th title="Quantidade contratada, distinta do estoque físico">Qtd</th><th>Valor Unit.</th><th>Subtotal</th><th>Ações</th></tr></thead><tbody>
<?php $hasItems=false; foreach ($items as $item): if ((int)$item['numero_pagina']!==(int)$sheet['numero_pagina']) { continue; } $hasItems=true; $pending=(int)$item['estoque_inicializado']===0; $uncertain=(int)$item['abertura_sem_comprovacao']===1; $balance=(int)$item['saldo']; $itemOpen=is_array($draft) && (int)$draft['item']===(int)$item['id']; ?>
<tr><td><strong><?= e($item['nome_produto']) ?><?= $item['excluido_em']!==null ? ' (excluído)' : '' ?></strong><small class="contract-physical-stock">Estoque físico: <?= $pending ? 'abertura pendente' : ($uncertain ? 'zero anterior sem comprovação' : $balance.' '.e($item['unidade'])) ?><?php if (!$pending && !$uncertain): ?><br><?= $balance===0 ? 'Saldo zero confirmado' : ($balance<=(int)$item['estoque_minimo'] ? 'Atenção: no mínimo ou abaixo' : 'Saldo confirmado') ?><?php endif; ?><br>Limites: <?= $item['estoque_minimo']===null ? '—' : (int)$item['estoque_minimo'] ?> / <?= $item['estoque_maximo']===null ? '—' : (int)$item['estoque_maximo'] ?></small></td><td><?= e($item['marca'] ?: '—') ?></td><td><span class="contract-unit-badge"><?= e($item['unidade']) ?></span></td>
<td><span title="Quantidade contratada"><?= e($item['quantidade_contratada'] ?? $item['quantidade']) ?></span></td>
<td><?= e(Contrato::money($item['preco_centavos']===null ? null : (int)$item['preco_centavos'])) ?></td><td class="contract-product-subtotal"><?= e(Contrato::money($item['total_centavos']===null ? null : (int)$item['total_centavos'])) ?></td><td><div class="contract-item-actions"><?php if ($active && $sheet['excluido_em']===null && $item['excluido_em']===null): ?><button type="button" class="btn-warning contract-btn-sm" data-contract-item-toggle="item-actions-<?= (int)$item['id'] ?>" aria-expanded="<?= $itemOpen ? 'true' : 'false' ?>">✏️ Editar</button><a class="btn-danger contract-btn-sm" href="#delete-product-<?= (int)$item['id'] ?>" data-open-details>🗑️ Apagar</a><?php else: ?><a href="<?= e(url('contrato/historico/'.$item['id'].($query ? '?'.http_build_query($query) : ''))) ?>">Histórico</a><?php endif; ?></div></td></tr>
<?php if ($active && $sheet['excluido_em']===null && $item['excluido_em']===null): ?>
<tr id="item-actions-<?= (int)$item['id'] ?>" class="contract-item-expanded"<?= $itemOpen ? '' : ' hidden' ?>><td colspan="7">
<p><a href="<?= e(url('contrato/historico/'.$item['id'].($query ? '?'.http_build_query($query) : ''))) ?>">Consultar histórico do produto</a></p>
<?php if ($isAdmin && $item['total_centavos']===null): ?><details><summary>Conciliar item legado</summary><p>Confirme a quantidade inteira e o preço unitário contra os documentos. O valor original permanece registrado.</p><form method="post" action="<?= e(url('contrato/conciliar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><label>Quantidade contratada <input name="quantidade" type="number" min="1" required></label><label>Preço unitário R$ <input name="preco" inputmode="decimal" required></label><button class="btn btn-primary">Conciliar item</button></form></details><?php endif; ?>
<?php $productCurrent=['nome'=>$item['nome_produto'],'marca'=>$item['marca'] ?? '','unidade'=>$item['unidade'],'quantidade'=>$item['quantidade_contratada'] ?? $item['quantidade'],'preco'=>$item['preco_centavos']===null ? '' : number_format((int)$item['preco_centavos']/100,2,',','')]; ?>
<details id="edit-product-<?= (int)$item['id'] ?>"<?= $draftOpen('editar-produto',(int)$item['id']) ?>><summary>Editar produto</summary><?php $draftNotice('editar-produto',(int)$item['id'],$productCurrent); ?><form method="post" action="<?= e(url('contrato/produto/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><label>Nome <input name="nome" required maxlength="150" value="<?= e($draftValue('editar-produto',(int)$item['id'],'nome',$productCurrent['nome'])) ?>"></label><label>Marca <input name="marca" maxlength="100" value="<?= e($draftValue('editar-produto',(int)$item['id'],'marca',$productCurrent['marca'])) ?>"></label><label>Unidade <input name="unidade" required maxlength="30" value="<?= e($draftValue('editar-produto',(int)$item['id'],'unidade',$productCurrent['unidade'])) ?>"></label><label>Quantidade contratada <input name="quantidade" type="number" min="1" required value="<?= e($draftValue('editar-produto',(int)$item['id'],'quantidade',$productCurrent['quantidade'])) ?>"></label><label>Preço R$ <input name="preco" required value="<?= e($draftValue('editar-produto',(int)$item['id'],'preco',$productCurrent['preco'])) ?>"></label><button class="btn btn-primary">Salvar produto</button></form></details>
<details id="stock-config-<?= (int)$item['id'] ?>"<?= $draftOpen('estoque',(int)$item['id']) ?>><summary>Configurar limites e abertura</summary>
<p><?= $pending ? 'Estoque ainda não conferido. Salvar apenas os limites mantém a abertura pendente.' : ($uncertain ? 'Abertura antiga sem comprovação. O administrador deve registrar a contagem física atual, zero ou positiva, com justificativa documental antes de novas movimentações.' : 'Abertura confirmada.') ?></p>
<?php $stockCurrent=['minimo'=>$item['estoque_minimo'] ?? '0','maximo'=>$item['estoque_maximo'] ?? '','abertura'=>'','confirmar_abertura'=>'']; $draftNotice('estoque',(int)$item['id'],$stockCurrent); ?>
<form method="post" action="<?= e(url('contrato/estoque/'.$record['id']).'#folha-'.$sheet['id']) ?>">
<input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>">
<label>Mínimo <input name="minimo" type="number" min="0" required value="<?= e($draftValue('estoque',(int)$item['id'],'minimo',$stockCurrent['minimo'])) ?>"></label><label>Máximo <input name="maximo" type="number" min="1" required value="<?= e($draftValue('estoque',(int)$item['id'],'maximo',$stockCurrent['maximo'])) ?>"></label>
<?php if ($pending && ($isAdmin || !$item['legado'])): ?><label>Saldo de abertura conferido <input name="abertura" type="number" min="0" value="<?= e($draftValue('estoque',(int)$item['id'],'abertura')) ?>"></label><label><input type="checkbox" name="confirmar_abertura" value="1"<?= $draftValue('estoque',(int)$item['id'],'confirmar_abertura')==='1' ? ' checked' : '' ?>> Confirmo que conferi o saldo de abertura informado, inclusive se for zero.</label><?php else: ?><input type="hidden" name="abertura" value=""><input type="hidden" name="confirmar_abertura" value=""><?php endif; ?>
<button class="btn btn-primary">Salvar configuração</button></form></details>
<?php if ($isAdmin && ($uncertain || $matchesDraft('conferir-abertura',(int)$item['id']))): ?><details id="old-opening-<?= (int)$item['id'] ?>"<?= $draftOpen('conferir-abertura',(int)$item['id']) ?>><summary>Conferir abertura antiga sem comprovação</summary><p>Registre a contagem física feita agora, inclusive zero, na unidade do produto e confira os limites. A operação registra autoria, horário atual e base documental; nenhum histórico é refeito.</p><?php $draftNotice('conferir-abertura',(int)$item['id'],['quantidade'=>$balance,'unidade'=>$item['unidade'],'minimo'=>$item['estoque_minimo'],'maximo'=>$item['estoque_maximo']]); ?><?php if ($uncertain): ?><form method="post" action="<?= e(url('contrato/conferir-abertura/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><label>Quantidade física conferida <input name="quantidade" type="number" min="0" required value="<?= e($draftValue('conferir-abertura',(int)$item['id'],'quantidade')) ?>"></label><label>Unidade conferida <input name="unidade" required maxlength="30" value="<?= e($draftValue('conferir-abertura',(int)$item['id'],'unidade',$item['unidade'])) ?>"></label><label>Mínimo <input name="minimo" type="number" min="0" required value="<?= e($draftValue('conferir-abertura',(int)$item['id'],'minimo',$item['estoque_minimo'] ?? '0')) ?>"></label><label>Máximo <input name="maximo" type="number" min="1" required value="<?= e($draftValue('conferir-abertura',(int)$item['id'],'maximo',$item['estoque_maximo'])) ?>"></label><label>Justificativa e documento da conferência <input name="motivo" minlength="10" maxlength="180" required value="<?= e($draftValue('conferir-abertura',(int)$item['id'],'motivo')) ?>"></label><label><input type="checkbox" name="confirmar" value="1" required<?= $draftValue('conferir-abertura',(int)$item['id'],'confirmar')==='1' ? ' checked' : '' ?>> Confirmo que realizei a contagem física atual na quantidade e unidade informadas.</label><button class="btn btn-warning">Registrar conferência atual</button></form><?php else: ?><p><strong>A abertura já foi conferida.</strong> Saldo atual: <?= $balance ?> <?= e($item['unidade']) ?>. A recuperação antiga está encerrada; use o histórico para consultar a conferência registrada.</p><?php endif; ?></details><?php endif; ?>
<?php if (!$pending && !$uncertain): ?><details id="move-stock-<?= (int)$item['id'] ?>"<?= $draftOpen('movimentar',(int)$item['id']) ?>><summary>Registrar entrada ou saída</summary><?php $draftNotice('movimentar',(int)$item['id'],['quantidade'=>'Saldo atual: '.$balance.' '.$item['unidade']]); ?><form method="post" action="<?= e(url('contrato/movimentar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><label>Tipo <select name="tipo"><option value="entrada"<?= $draftValue('movimentar',(int)$item['id'],'tipo','entrada')==='entrada' ? ' selected' : '' ?>>Entrada</option><option value="saida"<?= $draftValue('movimentar',(int)$item['id'],'tipo','entrada')==='saida' ? ' selected' : '' ?>>Saída</option></select></label><label>Quantidade positiva <input name="quantidade" type="number" min="1" required value="<?= e($draftValue('movimentar',(int)$item['id'],'quantidade')) ?>"></label><label>Origem ou destino <input name="motivo" minlength="3" maxlength="300" required value="<?= e($draftValue('movimentar',(int)$item['id'],'motivo')) ?>"></label><button class="btn btn-primary">Registrar</button></form></details><?php endif; ?>
<?php if ($isAdmin && !$pending && !$uncertain): ?><details id="reverse-stock-<?= (int)$item['id'] ?>"<?= $draftOpen('estornar',(int)$item['id']) ?>><summary>Estornar movimento</summary><?php $draftNotice('estornar',(int)$item['id'],[]); ?><form method="post" action="<?= e(url('contrato/movimentar/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$item['revisao'] ?>"><input type="hidden" name="tipo" value="estorno"><input type="hidden" name="quantidade" value="1"><input type="hidden" name="chave" value="<?= e(bin2hex(random_bytes(16))) ?>"><label>ID do movimento original <input name="original" type="number" min="1" required value="<?= e($draftValue('estornar',(int)$item['id'],'original')) ?>"></label><label>Justificativa <input name="motivo" minlength="3" maxlength="300" required value="<?= e($draftValue('estornar',(int)$item['id'],'motivo')) ?>"></label><button class="btn btn-warning">Estornar</button></form></details><?php endif; ?>
<details id="delete-product-<?= (int)$item['id'] ?>"><summary>Excluir produto</summary><p>O registro e o histórico serão preservados. Destine todo saldo físico antes de excluir.</p><form method="post" action="<?= e(url('contrato/excluir/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="produto" value="<?= (int)$item['id'] ?>"><label><input type="checkbox" name="confirmar" value="1" required> Confirmo a exclusão lógica deste produto</label><button class="btn-danger">Excluir produto</button></form></details>
</td></tr><?php endif; ?>
<?php endforeach; ?><?php if (!$hasItems): ?><tr><td colspan="7" class="contract-empty-products">Nenhum produto lançado nesta nota.</td></tr><?php endif; ?></tbody></table></div>
<?php if ($active && $sheet['excluido_em']===null): ?>
<details id="note-observation-<?= (int)$sheet['id'] ?>" class="contract-observation-card" open><summary>Observações da nota <?= (int)$sheet['numero_pagina'] ?></summary><?php $draftNotice('observacao',(int)$sheet['id'],['observacao'=>$sheet['observacao'] ?? '']); ?><form method="post" action="<?= e(url('contrato/editar-folha/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><input type="hidden" name="revisao" value="<?= (int)$sheet['revisao'] ?>"><textarea name="observacao" maxlength="2000" rows="3" class="form-control" aria-label="Observações da nota <?= (int)$sheet['numero_pagina'] ?>" placeholder="Escreva aqui informações adicionais desta nota..."><?= e($draftValue('observacao',(int)$sheet['id'],'observacao',$sheet['observacao'] ?? '')) ?></textarea><div class="contract-inline-actions"><button class="btn-primary">Salvar observações</button></div></form></details>
<details id="delete-note-<?= (int)$sheet['id'] ?>" class="contract-note-delete"><summary>Excluir nota</summary><p>A exclusão é lógica e preserva o histórico. Destine todo saldo físico dos produtos antes de continuar.</p><form method="post" action="<?= e(url('contrato/excluir/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="folha" value="<?= (int)$sheet['id'] ?>"><label><input type="checkbox" name="confirmar" value="1" required> Confirmo a exclusão lógica desta nota</label><button class="btn-danger">Excluir nota</button></form></details>
<?php else: ?><div class="contract-observation-card"><h4>Observações da nota <?= (int)$sheet['numero_pagina'] ?></h4><p><?= nl2br(e($sheet['observacao'] ?? '')) ?></p></div><?php endif; ?>
</section>
<?php endforeach; ?>
<?php if ($active): ?><div class="contract-secondary-actions"><details id="new-note"<?= $draftOpen('nova-folha',0) ?>><summary>Nova nota com observação</summary><?php $draftNotice('nova-folha',0,[]); ?><form method="post" action="<?= e(url('contrato/folha/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><input type="hidden" name="copiar" value=""><input type="hidden" name="chave" value=""><label for="observacao">Observação</label><textarea id="observacao" name="observacao" maxlength="2000" class="form-control"><?= e($draftValue('nova-folha',0,'observacao')) ?></textarea><button class="btn-primary">Adicionar nota</button></form></details>
<details id="delete-contract"><summary>Excluir pedido</summary><p>O registro e o histórico continuarão disponíveis. É preciso destinar todo saldo físico antes.</p><form method="post" action="<?= e(url('contrato/excluir/'.$record['id'])) ?>"><input type="hidden" name="_csrf_token" value="<?= e(csrf_token()) ?>"><?= $formContextField ?><input type="hidden" name="revisao" value="<?= (int)$record['revisao'] ?>"><label><input type="checkbox" name="confirmar" value="1" required> Confirmo a exclusão lógica</label><button class="btn-danger">Excluir pedido</button></form></details></div><?php endif; ?>
